version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FairSplit-server
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=FairSplit123
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - FairSplit-network
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:8080/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: FairSplit-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-FairSplit123}
    restart: always
    networks:
      - FairSplit-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  FairSplit-network:
    driver: bridge

volumes:
  node_modules:
  redis-data:
    driver: local
